---
variables:
  terraformEnvironment: dev
  terraformVersion: '1.1.0'

terraformValidate:
  stage: validate
  script:
    - terraform_${terraformVersion} -chdir=environments/${terraformEnvironment} init
    - terraform_${terraformVersion} -chdir=environments/${terraformEnvironment} validate
