---
variables:
  terraformEnvironment: dev
  terraformVersion: '1.1.0'

terraformApply:
  stage: deploy
  script:
    - terraform_${terraformVersion} -chdir=environments/${terraformEnvironment} init
    - terraform_${terraformVersion} -chdir=environments/${terraformEnvironment} apply -input=false -auto-approve
  only:
    - main
  when: manual
